### ISSUE TITLE
about SLAW

### ISSUE THREAD

**Issue by jinzbone** [Ryuuba/slaw#1]
An OMNeT++ implementation of the SLAM mobility model
You made a mistake on the title "SLAM" which is supposed to be SLAW :) 
Ps: I'm wondering are you implementing the SLAW mobility model for academic research or your own interest? I am reading papers about SLAW and want to implement it,too. 
Thanks for your share!

**Comment by Ryuuba** [comment]
Hi, thank you for tell me about my mistake. I'm implementing this mobility model for academic research. At this stage, the implementation generates flights statistically equivalent to the one implemented by the SLAW's authors. The next step is to measure the probability distribution of the intercontact time. Best regards!
